/**:
    ros__parameters:
      # Experimental setup param
      robot_id: 0
      nb_robots: 2
      intra_robot_loop_closure_detection: false
      # Communication/computation budget
      loop_closure_budget: 5
      detection_period: 5
      max_keyframe_queue_size: 10
      # Similarity settings
      similarity_threshold: 0.5
      similarity_loc: 1.0
      similarity_scale: 0.25
      # Global descriptor params
      global_descriptor_topic: '/global_descriptor'
      global_descriptor_technique: 'netvlad'
      image_crop_size: 376
      nn_checkpoint: '/home/lajoiepy/Documents/projects/SelfSupervisedPlaceRecognition/pytorch-NetVlad/runs/Nov24_23-21-16_vgg16_netvlad-Pit-Baseline/checkpoints/model_best.pth.tar'
      pca_checkpoint: '/home/lajoiepy/Documents/projects/SelfSupervisedPlaceRecognition/pytorch-NetVlad/pca.pkl'
      intra_loop_min_inbetween_keyframes: 20
      # Geometric verification params
      pnp_min_inliers: 6
      # Mapping params
      add_link_srv: '/rtabmap/add_link'